### ISSUE TITLE
How do I get honey bottles?

### ISSUE THREAD

**Issue by Izadumb1** [ShyDispatch/StarPounds#5]
Not an issue with the mod itself, just a question.

Trying to get to the honey squirt gun, but don't know how to make honey bottles. Help?

**Comment by ShyDispatch** [comment]
Honey bottles can be gathered from farming the little bees in either of the flowery mini biomes.

**Comment by Izadumb1** [comment]
AH, thanks

**Comment by Izadumb1** [comment]
I wish it was easier to gather. I don't like that the bottled honey's locked behind grinding. I wish I could just make/buy it.
